#############################################################################
# Makefile for building: UltrasoundStation
# Generated by qmake (2.01a) (Qt 4.7.0) on: ?? ?? 26 17:41:17 2011
# Project:  UltrasoundStation.pro
# Template: subdirs
# Command: c:\qt\2010.05\qt\bin\qmake.exe -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ -o Makefile UltrasoundStation.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\qt\2010.05\qt\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-UltrasoundStation_ClientSystem

UltrasoundStation_ClientSystem\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) UltrasoundStation_ClientSystem\ $(MKDIR) UltrasoundStation_ClientSystem\ 
	cd UltrasoundStation_ClientSystem\ && $(QMAKE) e:\GraduateDesign\UltrasoundStation\UltrasoundStation_ClientSystem\UltrasoundStation_ClientSystem.pro -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ -o $(MAKEFILE)
sub-UltrasoundStation_ClientSystem-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) UltrasoundStation_ClientSystem\ $(MKDIR) UltrasoundStation_ClientSystem\ 
	cd UltrasoundStation_ClientSystem\ && $(QMAKE) e:\GraduateDesign\UltrasoundStation\UltrasoundStation_ClientSystem\UltrasoundStation_ClientSystem.pro -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ -o $(MAKEFILE)
sub-UltrasoundStation_ClientSystem: UltrasoundStation_ClientSystem\$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem\ && $(MAKE) -f $(MAKEFILE)
sub-UltrasoundStation_ClientSystem-make_default: UltrasoundStation_ClientSystem\$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem\ && $(MAKE) -f $(MAKEFILE) 
sub-UltrasoundStation_ClientSystem-make_first: UltrasoundStation_ClientSystem\$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem\ && $(MAKE) -f $(MAKEFILE) first
sub-UltrasoundStation_ClientSystem-all: UltrasoundStation_ClientSystem\$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem\ && $(MAKE) -f $(MAKEFILE) all
sub-UltrasoundStation_ClientSystem-clean: UltrasoundStation_ClientSystem\$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem\ && $(MAKE) -f $(MAKEFILE) clean
sub-UltrasoundStation_ClientSystem-distclean: UltrasoundStation_ClientSystem\$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem\ && $(MAKE) -f $(MAKEFILE) distclean
sub-UltrasoundStation_ClientSystem-install_subtargets: UltrasoundStation_ClientSystem\$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem\ && $(MAKE) -f $(MAKEFILE) install
sub-UltrasoundStation_ClientSystem-uninstall_subtargets: UltrasoundStation_ClientSystem\$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: UltrasoundStation.pro  c:/Qt/2010.05/qt/mkspecs/win32-g++/qmake.conf c:/Qt/2010.05/qt/mkspecs/qconfig.pri \
		c:/Qt/2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		c:/Qt/2010.05/qt/mkspecs/features/qt_functions.prf \
		c:/Qt/2010.05/qt/mkspecs/features/qt_config.prf \
		c:/Qt/2010.05/qt/mkspecs/features/exclusive_builds.prf \
		c:/Qt/2010.05/qt/mkspecs/features/default_pre.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/default_pre.prf \
		c:/Qt/2010.05/qt/mkspecs/features/debug.prf \
		c:/Qt/2010.05/qt/mkspecs/features/debug_and_release.prf \
		c:/Qt/2010.05/qt/mkspecs/features/default_post.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/default_post.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/rtti.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/exceptions.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/stl.prf \
		c:/Qt/2010.05/qt/mkspecs/features/shared.prf \
		c:/Qt/2010.05/qt/mkspecs/features/warn_on.prf \
		c:/Qt/2010.05/qt/mkspecs/features/qt.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/thread.prf \
		c:/Qt/2010.05/qt/mkspecs/features/moc.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/windows.prf \
		c:/Qt/2010.05/qt/mkspecs/features/resources.prf \
		c:/Qt/2010.05/qt/mkspecs/features/uic.prf \
		c:/Qt/2010.05/qt/mkspecs/features/yacc.prf \
		c:/Qt/2010.05/qt/mkspecs/features/lex.prf \
		c:/Qt/2010.05/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ -o Makefile UltrasoundStation.pro
c:\Qt\2010.05\qt\mkspecs\qconfig.pri:
c:\Qt\2010.05\qt\mkspecs\modules\qt_webkit_version.pri:
c:\Qt\2010.05\qt\mkspecs\features\qt_functions.prf:
c:\Qt\2010.05\qt\mkspecs\features\qt_config.prf:
c:\Qt\2010.05\qt\mkspecs\features\exclusive_builds.prf:
c:\Qt\2010.05\qt\mkspecs\features\default_pre.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\default_pre.prf:
c:\Qt\2010.05\qt\mkspecs\features\debug.prf:
c:\Qt\2010.05\qt\mkspecs\features\debug_and_release.prf:
c:\Qt\2010.05\qt\mkspecs\features\default_post.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\default_post.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\rtti.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\exceptions.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\stl.prf:
c:\Qt\2010.05\qt\mkspecs\features\shared.prf:
c:\Qt\2010.05\qt\mkspecs\features\warn_on.prf:
c:\Qt\2010.05\qt\mkspecs\features\qt.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\thread.prf:
c:\Qt\2010.05\qt\mkspecs\features\moc.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\windows.prf:
c:\Qt\2010.05\qt\mkspecs\features\resources.prf:
c:\Qt\2010.05\qt\mkspecs\features\uic.prf:
c:\Qt\2010.05\qt\mkspecs\features\yacc.prf:
c:\Qt\2010.05\qt\mkspecs\features\lex.prf:
c:\Qt\2010.05\qt\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ -o Makefile UltrasoundStation.pro

qmake_all: sub-UltrasoundStation_ClientSystem-qmake_all FORCE

make_default: sub-UltrasoundStation_ClientSystem-make_default FORCE
make_first: sub-UltrasoundStation_ClientSystem-make_first FORCE
all: sub-UltrasoundStation_ClientSystem-all FORCE
clean: sub-UltrasoundStation_ClientSystem-clean FORCE
distclean: sub-UltrasoundStation_ClientSystem-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-UltrasoundStation_ClientSystem-install_subtargets FORCE
uninstall_subtargets: sub-UltrasoundStation_ClientSystem-uninstall_subtargets FORCE

sub-UltrasoundStation_ClientSystem-sub_Debug: UltrasoundStation_ClientSystem\$(MAKEFILE)
	cd UltrasoundStation_ClientSystem\ && $(MAKE) debug
debug: sub-UltrasoundStation_ClientSystem-sub_Debug

sub-UltrasoundStation_ClientSystem-sub_Release: UltrasoundStation_ClientSystem\$(MAKEFILE)
	cd UltrasoundStation_ClientSystem\ && $(MAKE) release
release: sub-UltrasoundStation_ClientSystem-sub_Release

sub-UltrasoundStation_ClientSystem-check: UltrasoundStation_ClientSystem\$(MAKEFILE)
	cd UltrasoundStation_ClientSystem\ && $(MAKE) check
check: sub-UltrasoundStation_ClientSystem-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

