#############################################################################
# Makefile for building: UltrasoundStation
# Generated by qmake (2.01a) (Qt 4.7.3) on: ?? 9? 2 10:36:37 2011
# Project:  UltrasoundStation.pro
# Template: subdirs
# Command: /home/flyfish/QtSDK/Desktop/Qt/473/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile UltrasoundStation.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /home/flyfish/QtSDK/Desktop/Qt/473/gcc/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-UltrasoundStation_ClientSystem

UltrasoundStation_ClientSystem/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) UltrasoundStation_ClientSystem/ || $(MKDIR) UltrasoundStation_ClientSystem/ 
	cd UltrasoundStation_ClientSystem/ && $(QMAKE) /home/flyfish/Git_Project/UltrasoundStation/UltrasoundStation_ClientSystem/UltrasoundStation_ClientSystem.pro -spec ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-UltrasoundStation_ClientSystem-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) UltrasoundStation_ClientSystem/ || $(MKDIR) UltrasoundStation_ClientSystem/ 
	cd UltrasoundStation_ClientSystem/ && $(QMAKE) /home/flyfish/Git_Project/UltrasoundStation/UltrasoundStation_ClientSystem/UltrasoundStation_ClientSystem.pro -spec ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-UltrasoundStation_ClientSystem: UltrasoundStation_ClientSystem/$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem/ && $(MAKE) -f $(MAKEFILE)
sub-UltrasoundStation_ClientSystem-make_default: UltrasoundStation_ClientSystem/$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem/ && $(MAKE) -f $(MAKEFILE) 
sub-UltrasoundStation_ClientSystem-make_first: UltrasoundStation_ClientSystem/$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem/ && $(MAKE) -f $(MAKEFILE) first
sub-UltrasoundStation_ClientSystem-all: UltrasoundStation_ClientSystem/$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem/ && $(MAKE) -f $(MAKEFILE) all
sub-UltrasoundStation_ClientSystem-clean: UltrasoundStation_ClientSystem/$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem/ && $(MAKE) -f $(MAKEFILE) clean
sub-UltrasoundStation_ClientSystem-distclean: UltrasoundStation_ClientSystem/$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem/ && $(MAKE) -f $(MAKEFILE) distclean
sub-UltrasoundStation_ClientSystem-install_subtargets: UltrasoundStation_ClientSystem/$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem/ && $(MAKE) -f $(MAKEFILE) install
sub-UltrasoundStation_ClientSystem-uninstall_subtargets: UltrasoundStation_ClientSystem/$(MAKEFILE) FORCE
	cd UltrasoundStation_ClientSystem/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: UltrasoundStation.pro  ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++/qmake.conf ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile UltrasoundStation.pro
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile UltrasoundStation.pro

qmake_all: sub-UltrasoundStation_ClientSystem-qmake_all FORCE

make_default: sub-UltrasoundStation_ClientSystem-make_default FORCE
make_first: sub-UltrasoundStation_ClientSystem-make_first FORCE
all: sub-UltrasoundStation_ClientSystem-all FORCE
clean: sub-UltrasoundStation_ClientSystem-clean FORCE
distclean: sub-UltrasoundStation_ClientSystem-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-UltrasoundStation_ClientSystem-install_subtargets FORCE
uninstall_subtargets: sub-UltrasoundStation_ClientSystem-uninstall_subtargets FORCE

sub-UltrasoundStation_ClientSystem-check: UltrasoundStation_ClientSystem/$(MAKEFILE)
	cd UltrasoundStation_ClientSystem/ && $(MAKE) check
check: sub-UltrasoundStation_ClientSystem-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

